version: '3.8'
services:
  backend-app:
    build: .
    container_name: backend_service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - eval-net

networks:
  eval-net:
    external: true