version: '3.8'
services:
  backend-app:
    image: ${DOCKER_USER}/innovatech-backend:latest
    container_name: backend_service
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST_PRIVATE_IP}
      - DB_USER=innovatech_user
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=innovatech_db
    networks:
      - deploy-net

networks:
  deploy-net:
    driver: bridge